version: 2.1
commands:
  build_linux:
    description: Build on Linux
    parameters:
      compiler:
        description: The compiler to use
        type: enum
        enum: ["gcc", "clang"]
      build_type:
        description: Build type
        type: enum
        enum: ["Debug", "Release"]
        default: Release
    steps:
      - run:
          name: Install system dependencies
          command: >
            apt-get update && apt-get install -y build-essential git cmake &&
            if [ "<< parameters.compiler >>" = "clang" ]; then apt-get install -y clang && echo "export CC=/usr/bin/clang" >> $BASH_ENV && echo "export CXX=/usr/bin/clang++" >> $BASH_ENV; fi
      - checkout
      - run:
          name: CMake configure
          working_directory: build
          command: >
            flags="-Wall -Wextra -Wno-unused-parameter" &&
            cmake
            -DCMAKE_BUILD_TYPE=<< parameters.build_type >>
            -DCMAKE_C_FLAGS="${flags}"
            -DCMAKE_CXX_FLAGS="${flags}"
            ..
      - run:
          name: CMake build
          working_directory: build
          command: cmake --build . --parallel 2
      - run:
          name: CTest
          working_directory: build
          command: ctest -VV
jobs:
  build-gcc:
    docker:
      - image: debian:buster
    steps:
      - build_linux:
          compiler: gcc
          build_type: Release
  build-clang:
    docker:
      - image: debian:buster
    steps:
      - build_linux:
          compiler: clang
          build_type: Release
  build-doc:
      docker:
        - image: emgre/circleci-doxygen:0.0.3
      steps:
        - add_ssh_keys:
            fingerprints:
              - "ff:3e:7d:09:6d:e4:91:c3:73:6a:5d:cf:13:bd:c4:47"
        - checkout
        - run:
            name: Initialize m.css submodule
            command: git submodule update --init deps/m.css
        - run:
            name: Clone gh-pages branch
            command: git clone -b gh-pages-private $CIRCLE_REPOSITORY_URL build/doc/html
        - run:
            name: Build documentation
            command: python3 deps/m.css/doxygen/dox2html5.py Doxyfile-mcss
        - run:
            name: Push documentation to GitHub Pages
            command: sh ../../../.circleci/push-doc-to-gh-pages.sh
            working_directory: build/doc/html
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-gcc
      - build-clang
      - build-doc:
          requires:
            - build-gcc
            - build-clang
          filters:
            branches:
              only: master
