version: 2
jobs:
  build-gcc-debug:
    docker:
      - image: emgre/circleci-gcc:0.0.1
    steps:
      - checkout
      - run:
          name: Initialize submodules
          command: git submodule update --init
      - run:
          name: Configure
          command: cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS="-Wall" -DCMAKE_CXX_FLAGS="-Wall" ..
          working_directory: build
      - run:
          name: Build
          command: cmake --build . -- -j2
          working_directory: build
      - run:
          name: Test
          command: ctest -VV .
          working_directory: build
  build-gcc-release:
    docker:
      - image: emgre/circleci-gcc:0.0.1
    steps:
      - checkout
      - run:
          name: Initialize submodules
          command: git submodule update --init
      - run:
          name: Configure
          command: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-Wall" -DCMAKE_CXX_FLAGS="-Wall" ..
          working_directory: build
      - run:
          name: Build
          command: cmake --build . -- -j2
          working_directory: build
      - run:
          name: Test
          command: ctest -VV .
          working_directory: build
  build-clang-debug:
    docker:
      - image: emgre/circleci-clang:0.0.1
    steps:
      - checkout
      - run:
          name: Initialize submodules
          command: git submodule update --init
      - run:
          name: Configure
          command: cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS="-Wall" -DCMAKE_CXX_FLAGS="-Wall" ..
          working_directory: build
      - run:
          name: Build
          command: cmake --build . -- -j2
          working_directory: build
      - run:
          name: Test
          command: ctest -VV .
          working_directory: build
  build-clang-release:
    docker:
      - image: emgre/circleci-clang:0.0.1
    steps:
      - checkout
      - run:
          name: Initialize submodules
          command: git submodule update --init
      - run:
          name: Configure
          command: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-Wall" -DCMAKE_CXX_FLAGS="-Wall" ..
          working_directory: build
      - run:
          name: Build
          command: cmake --build . -- -j2
          working_directory: build
      - run:
          name: Test
          command: ctest -VV .
          working_directory: build
  build-doc:
      docker:
        - image: emgre/circleci-doxygen:0.0.1
      steps:
        - add_ssh_keys:
            fingerprints:
              - "72:a7:84:8d:f6:c0:55:b1:03:67:77:a0:98:ec:d7:b7"
        - checkout
        - run:
            name: Initialize m.css submodule
            command: git submodule update --init deps/m.css
        - run:
            name: Clone gh-pages branch
            command: git clone -b gh-pages $CIRCLE_REPOSITORY_URL build/doc/html
        - run:
            name: Build documentation
            command: python3 deps/m.css/doxygen/dox2html5.py Doxyfile-mcss
        - run:
            name: Push documentation to GitHub Pages
            command: sh ../../../.circleci/push-doc-to-gh-pages.sh
            working_directory: build/doc/html
workflows:
  version: 2
  build_and_test:
    jobs:
      #- build-gcc-debug
      #- build-gcc-release
      #- build-clang-debug
      #- build-clang-release
      - build-doc
          #requires:
          #  - build-gcc-debug
          #  - build-gcc-release
          #  - build-clang-debug
          #  - build-clang-release
