#ifndef MODBUS_CONNECTIONEXCEPTION_H
#define MODBUS_CONNECTIONEXCEPTION_H

/** @file
 * @brief Class @ref modbus::ConnectionException
 */

#include "modbus/exceptions/IException.h"

namespace modbus
{

/**
 * @brief Connection error
 *
 * Represents a connection error. It can happen because an host is unreachable, the network
 * adapter is faulty, the other end closed the connection, etc.
 *
 * Calling @ref IException::get_message() for a human-readable message. Note that the message
 * will probably be generated by the operating system and may be internationalized.
 */
class ConnectionException : public IException
{
public:
    /**
     * @brief Constructor
     * @param message Human-readable error message
     */
    ConnectionException(const std::string& message) : IException{message} {}
};

} // namespace modbus

#endif //MODBUS_CONNECTIONEXCEPTION_H
