/*
 * Copyright 2017-2018 Duke Energy Corporation and Open Energy Solutions, Inc.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef MODBUS_CONNECTIONEXCEPTION_H
#define MODBUS_CONNECTIONEXCEPTION_H

/** @file
 * @brief Class @ref modbus::ConnectionException
 */

#include "modbus/exceptions/IException.h"

namespace modbus
{

/**
 * @brief Connection error
 *
 * Represents a connection error. It can happen because an host is unreachable, the network
 * adapter is faulty, the other end closed the connection, etc.
 *
 * Calling @ref IException::get_message() for a human-readable message. Note that the message
 * will probably be generated by the operating system and may be internationalized.
 */
class ConnectionException : public IException
{
public:
    /**
     * @brief Constructor
     * @param message Human-readable error message
     */
    ConnectionException(const std::string& message) : IException{message} {}
};

} // namespace modbus

#endif //MODBUS_CONNECTIONEXCEPTION_H
